### PR TITLE
Get rid of compile errors and warnings, add test framework

### LINKED ISSUE #13: mark contract method visibility / purity

### PR DESCRIPTION
**Pull request by Jake-Gillberg**
fixes #13 

Gets contracts Compiling, and adds a test framework, adds OpenZeppelin ERC20 tests #8

### CODE REVIEW

**Comment by edzillion** [comment]
Have you run the travis build yet? Where is it building? I set up an org here: https://travis-ci.org/CirclesUBI

**Comment by Jake-Gillberg** [comment]
@edzillion Yup, I have. I'm not sure how travis works, but if you click some of the "checks passed" links here in this pull request it should take you to the travis info: https://travis-ci.com/CirclesUBI/circles-contracts/builds/86016136?utm_source=github_status&utm_medium=notification

**Comment by edzillion** [comment]
> 
> 
> @edzillion Yup, I have. I'm not sure how travis works, but if you click some of the "checks passed" links here in this pull request it should take you to the travis info: https://travis-ci.com/CirclesUBI/circles-contracts/builds/86016136?utm_source=github_status&utm_medium=notification

oh yeah, obviously :p

**Comment by Jake-Gillberg** [comment]
This was about 20hrs of work

**Pull request merged**
