### PR TITLE
Update node version

### PR DESCRIPTION
**Pull request by llunaCreixent**
Circles-contracts works well with Node 11 (Debian), 12 (MacOS), but has problems with Node 14 (Debian).

**Tasks:**

* [x] Correct NodeJs version in README.md and other documents (.nvmrc; and .github/workflows/run-tests.yml in `migrate-to-gh-actions` branch).
* [x] Trace down the broken dependencies using `npm list <package_name>` in order to upgrade to higher NodeJs version.
* [ ] Fix broken tests after dependency updates

### CODE REVIEW

**Comment by llunaCreixent** [comment]
**logs of `npm install` include:**

```
Failed at the keccak@1.4.0 rebuild script.
```

**Current state of the dependencies that cause problems**

```
$ npm list keccak
circles-contracts@2.3.1 /home/.../circles-contracts
├─┬ @truffle/hdwallet-provider@1.2.0
│ └─┬ ethereum-cryptography@0.1.3
│   └── keccak@3.0.1 
└─┬ ganache-cli@6.10.1
  └─┬ ethereumjs-util@6.1.0
    └── keccak@1.4.0 
```

```
$ npm list scrypt
circles-contracts@2.3.1 /home/.../circles-contracts
└─┬ ganache-cli@6.10.1
  └── UNMET OPTIONAL DEPENDENCY scrypt@6.0.3 
```

**Comment by llunaCreixent** [comment]
Apparently, the owner of the repo struggles with updating `scrypt` NPM package.

See: 
- https://github.com/barrysteyn/node-scrypt/pull/197
- https://github.com/ChainSafe/web3.js/issues/3408

**Comment by llunaCreixent** [comment]
For the ganache-cli update:
* https://github.com/trufflesuite/ganache-cli/pull/789
* https://github.com/trufflesuite/ganache-cli/issues/785
* https://github.com/trufflesuite/ganache-cli/issues/697
* Changelog: https://github.com/trufflesuite/ganache-cli/releases

**Comment by adzialocha** [comment]
When updating the dependencies (especially `ganache-cli` to resolve the problem with `scrypt`) to:

```diff
   "devDependencies": {
-    "chai": "^4.1.2",
-    "chai-bignumber": "^2.0.2",
-    "chai-bn": "^0.1.1",
+    "chai": "^4.3.3",
+    "chai-bignumber": "^3.0.0",
+    "chai-bn": "^0.2.1",
     "dotenv": "^8.2.0",
-    "eslint-config-airbnb-base": "^14.0.0",
-    "eslint-plugin-import": "^2.18.2",
-    "ganache-cli": "^6.10.1",
-    "truffle": "^5.1.40"
+    "eslint-config-airbnb-base": "^14.2.1",
+    "eslint-plugin-import": "^2.22.1",
+    "ganache-cli": "^6.12.2",
+    "truffle": "^5.2.3"
   },
   "dependencies": {
     "@circles/safe-contracts": "^1.0.14",
-    "@openzeppelin/contracts": "^3.1.0-solc-0.7",
-    "@truffle/contract": "^4.2.21",
-    "@truffle/error": "0.0.9",
-    "@truffle/hdwallet-provider": "^1.2.0",
-    "bluebird": "^3.7.1",
+    "@openzeppelin/contracts": "^3.4.1",
+    "@truffle/contract": "^4.3.9",
+    "@truffle/error": "0.0.12",
+    "@truffle/hdwallet-provider": "^1.2.2",
+    "bluebird": "^3.7.2",
     "ethereumjs-abi": "^0.6.8",
     "truffle-contract": "^4.0.31",
-    "web3-eth-abi": "^1.3.0"
+    "web3-eth-abi": "^1.3.4"
   }
```

The tests fail (both on Node 11 and 12):

```
  245 passing (7m)
  3 failing

  1) Contract: UBI
       ubi payouts
         should not update inflationOffset if exactly one period has passed:

      AssertionError: expected <BN: 1d5fb8d3e> to satisfy [Function]
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/UBI.js:163:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) Contract: UBI
       ubi payouts
         should update inflationOffset by x if period+x has passed:

      AssertionError: expected <BN: 1d5fb8b49> to satisfy [Function]
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/UBI.js:181:31)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) Contract: UBI
       ubi payouts - with different config params
         should update lastTouched by period+z if more x but less than y periods have passed:

      AssertionError: expected <BN: 8dbd186a39> to satisfy [Function]
      + expected - actual

      -false
      +true

      at Context.<anonymous> (test/UBI.js:443:36)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by llunaCreixent** [comment]
Updated ganache-cli:
```bash
npm install ganache-cli
```
and now the keccak package is updated:
```bash
$ npm list keccak
circles-contracts@2.3.1 /home/.../circles-contracts
├─┬ @truffle/hdwallet-provider@1.2.0
│ └─┬ ethereum-cryptography@0.1.3
│   └── keccak@3.0.1 
└─┬ ganache-cli@6.12.2
  └─┬ ethereumjs-util@6.2.1
    └─┬ ethereum-cryptography@0.1.3
      └── keccak@3.0.1 
```
```bash
$ npm list 
```
and tests ...

**Review by adzialocha — CHANGES_REQUESTED** [review]
Wow! :sparkles: Can you reflect that version of `ganache-cli` in `package.json` as well?

**Comment by llunaCreixent** [comment]
Still some warnings... 😉 but no errors 😀

**Review by adzialocha — APPROVED** [review]

**Review by louilinn — APPROVED** [review]

**Pull request merged**
